language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install: 
  - export JYTHON_URL='http://search.maven.org/remotecontent?filepath=org/python/jython-installer/2.5.3/jython-installer-2.5.3.jar'
  - wget $JYTHON_URL -O jython_installer.jar; java -jar jython_installer.jar -s -d $HOME/jython; export PATH=$HOME/jython:$PATH;
branches:
  only:
      - master
install:
  - "pip install -r touchforms/test_requirements.txt"
script: "./run_tests.sh"
